name: sms_god
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  telephony: 
    path: ../telephony
  dio: ^4.0.4
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  get_phone_number: ^2.0.1
  flutter_incoming_call: ^0.1.1
  # autop utils package
  autop_free_dart_utils:
    git: http://124.222.125.64:3412/autop/AutopFreeDartUtils.git
  autop_free_flutter_utils:
    git: http://124.222.125.64:3412/autop/AutopFreeFlutterUtils.git
  hive: ^2.2.3
  provider: ^6.0.3
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:

  uses-material-design: true
