// ignore_for_file: constant_identifier_names

import 'enum_make.dart';

enum HttpMethods {
  ACL,
  BASELINECONTROL,
  BIND,
  CHECKIN,
  CHECKOUT,
  CONNECT,
  COPY,
  DELETE,
  GET,
  HEAD,
  LABEL,
  LINK,
  LOCK,
  MERGE,
  MKACTIVITY,
  MKCALENDAR,
  MKCOL,
  MKREDIRECTREF,
  MKWORKSPACE,
  MOVE,
  OPTIONS,
  ORDERPATCH,
  PATCH,
  POST,
  PRI,
  PROPFIND,
  PROPPATCH,
  PUT,
  REBIND,
  REPORT,
  SEARCH,
  TRACE,
  UNBIND,
  UNCHECKOUT,
  UNLINK,
  UNLOCK,
  UPDATE,
  UPDATEREDIRECTREF,
  VERSIONCONTROL,
}

final routerMethodsEnum = makeEnumMap({
  HttpMethods.ACL: 'ACL',
  HttpMethods.BASELINECONTROL: 'BASELINE-CONTROL',
  HttpMethods.BIND: 'BIND',
  HttpMethods.CHECKIN: 'CHECKIN',
  HttpMethods.CHECKOUT: 'CHECKOUT',
  HttpMethods.CONNECT: 'CONNECT',
  HttpMethods.COPY: 'COPY',
  HttpMethods.DELETE: 'DELETE',
  HttpMethods.GET: 'GET',
  HttpMethods.HEAD: 'HEAD',
  HttpMethods.LABEL: 'LABEL',
  HttpMethods.LINK: 'LINK',
  HttpMethods.LOCK: 'LOCK',
  HttpMethods.MERGE: 'MERGE',
  HttpMethods.MKACTIVITY: 'MKACTIVITY',
  HttpMethods.MKCALENDAR: 'MKCALENDAR',
  HttpMethods.MKCOL: 'MKCOL',
  HttpMethods.MKREDIRECTREF: 'MKREDIRECTREF',
  HttpMethods.MKWORKSPACE: 'MKWORKSPACE',
  HttpMethods.MOVE: 'MOVE',
  HttpMethods.OPTIONS: 'OPTIONS',
  HttpMethods.ORDERPATCH: 'ORDERPATCH',
  HttpMethods.PATCH: 'PATCH',
  HttpMethods.POST: 'POST',
  HttpMethods.PRI: 'PRI',
  HttpMethods.PROPFIND: 'PROPFIND',
  HttpMethods.PROPPATCH: 'PROPPATCH',
  HttpMethods.PUT: 'PUT',
  HttpMethods.REBIND: 'REBIND',
  HttpMethods.REPORT: 'REPORT',
  HttpMethods.SEARCH: 'SEARCH',
  HttpMethods.TRACE: 'TRACE',
  HttpMethods.UNBIND: 'UNBIND',
  HttpMethods.UNCHECKOUT: 'UNCHECKOUT',
  HttpMethods.UNLINK: 'UNLINK',
  HttpMethods.UNLOCK: 'UNLOCK',
  HttpMethods.UPDATE: 'UPDATE',
  HttpMethods.UPDATEREDIRECTREF: 'UPDATEREDIRECTREF',
  HttpMethods.VERSIONCONTROL: 'VERSION-CONTROL'
}, HttpMethods.values);
