name: sms_center
description: A simple command-line application.

version: 1.0.0

environment:
  sdk: '>=2.17.0-104.0.dev <3.0.0'


dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
